### ISSUE TITLE
make vote page accessible on IE and Edge

### ISSUE THREAD

**Issue by Haroenv** [gin-fizz/pollistics#91]
~~ids and for isn't allowed to have spaces there, so we can just make it `optionXX` with XX being a counter there. Similar to how the inputs are done~~

IE and Edge don't support inline svg urls, use the final version used here https://codepen.io/tigt/post/optimizing-svgs-in-data-uris

TL;DR? make sure that ' is used for attributes and encode < and >to %3C and %3E

**Comment by elsmr** [comment]
# fuck IE

**Comment by Haroenv** [comment]
Okay, but this and `<details>` is the only thing missing, both with open PR's
